49722 initiate creation large media exchange set part1
UKHO/exchange-set-service pull request #143
Opened 2022-07-08 14:05 UTC by shailen14599

Code Changes for Initial large media folder and media.txt part 1
Unit Tests Changes
Functional Tests added

2022-07-11 12:51 UTC, sumod13943 approved these changes
LGTM

2022-07-11 14:06 UTC, ajasonca requested changes
A few comments for you to look at

2022-07-12 06:53 UTC, harshal11869 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.Common/Helpers/AzureBlobStorageService.cs
> +                return (largeExchangeSetInstance.GetInstanceNumber(1), ExchangeSetType.lxs);
For POS we are using same Large Exchange Set Instance-1 we need to use it as it is, and large media exchange set comes under lxs only. Just the size of exchange set and folder structure will be different hence not changed it.

2022-07-12 06:55 UTC, harshal11869 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.FulfilmentService/FulfilmentServiceJob.cs
> +            CommonHelper.IsPeriodicOutputService = fileSizeInMb > periodicOutputServiceConfiguration.Value.LargeMediaExchangeSetSizeInMB;
Actually we are going to use this IsPeriodicOutputService flag for further processing while creating large media exchange set e.g. Downloading ENCs Files

2022-07-12 06:56 UTC, harshal11869 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.FulfilmentService/Services/FulfilmentDataService.cs
> +            if (CommonHelper.IsPeriodicOutputService)
As suggested created new method (CreateLargeExchangeSet) to generate Large Media Exchange Set.

2022-07-12 06:57 UTC, harshal11869 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.FulfilmentService/Services/FulfilmentAncillaryFiles.cs
> +        public async Task<bool> CreateMediaFile(string batchId, string folderpath, string correlationId, string exchangeset)
Resolved.

2022-07-12 06:57 UTC, harshal11869 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.FulfilmentService/Services/FulfilmentAncillaryFiles.cs
> +        private readonly IOptions<PeriodicOutputServiceConfiguration> periodicOutputServiceConfiguration;
Resolved.

2022-07-12 06:58 UTC, harshal11869 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.FulfilmentService/Services/FulfilmentAncillaryFiles.cs
> +                var mediaFileContent = String.Format("GBWK{0:D2}_{1}   {2:D4}{3:D2}{4:D2}BASE      M0{5}X02",
As suggested used string interpolation for constructing string for MEDIA.TXT content.

2022-07-12 06:58 UTC, harshal11869 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.FulfilmentService/Services/FulfilmentAncillaryFiles.cs
> +                int substringvalue = 2;
Resolved

2022-07-12 06:58 UTC, harshal11869 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.FulfilmentService/Services/FulfilmentDataService.cs
> +            this.periodicOutputServiceConfiguration = periodicOutputServiceConfiguration;
Resolved.

2022-07-12 06:59 UTC, harshal11869 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.FulfilmentService/Services/FulfilmentDataService.cs
> +        public async Task CreatePosFolderStructure(string largeMediaExchangeSetPath)
Resolved.

2022-07-12 10:30 UTC, ajasonca approved these changes

2022-07-12 10:30 UTC, merged