51121 - Download ENC files from FSS for LargeMediaExchangSset
UKHO/exchange-set-service pull request #146
Opened 2022-07-15 06:36 UTC by shailen14599

Code changes & Unit Tests
Functional Tests

1. Removed temporary code for base folder creation 
2. Added temporary code for SCS BundleInfo generation to handle product location

2022-07-15 08:12 UTC, harshal11869 approved these changes
LGTM

2022-07-18 10:43 UTC, ajasonca requested changes
Some minor issues to clean up

2022-07-18 10:43 UTC, ajasonca commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.Webjob.UnitTests/Services/FulfilmentDataServiceTest.cs
> +                            new Dates{ UpdateNumber= 4, UpdateApplicationDate= DateTime.Today, IssueDate = DateTime.Today}},
The indentation is a bit off in this block - could you fix please

2022-07-18 11:52 UTC, Arit14975 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API.FunctionalTests/FunctionalTests/ExchangeSetForLargeFile.cs
> +                        string[] checksubDirectories = FssBatchHelper.CheckforDirectories(Path.Combine(DownloadedFolderPath, $"B{baseNumber}", Config.ExchangeSetEncRootFolder, folder));
Updated. Thanks

2022-07-18 11:52 UTC, Arit14975 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API.FunctionalTests/FunctionalTests/ExchangeSetForLargeFile.cs
> +                            string[] checkupdateDirectories = FssBatchHelper.CheckforDirectories(Path.Combine(DownloadedFolderPath, $"B{baseNumber}", Config.ExchangeSetEncRootFolder, folder, updateFo
Updated. Thanks

2022-07-18 15:28 UTC, ajasonca approved these changes
Looks good

2022-07-18 15:45 UTC, merged