generate enc update list csv
UKHO/exchange-set-service pull request #164
Opened 2022-09-05 06:08 UTC by MastekRohitChettri

This is ESS side of  Pbi => 52229 - POS Upload Batch 4 - catalogue file.

Code changes and Unit tests
Functional Test

2022-09-05 12:22 UTC, harshal11869 requested changes

2022-09-05 12:22 UTC, harshal11869 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.FulfilmentService/Services/FulfilmentAncillaryFiles.cs
> +            string file = Path.Combine(filePath, "ENC Updates List.csv");
```suggestion
            string file = Path.Combine(filePath, "ENC Update List.csv");
```

2022-09-05 12:48 UTC, MastekRohitChettri commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API.FunctionalTests/appsettings.json
> +    "EncUpdateList": "ENC Updates List.csv"
Resolved

2022-09-05 12:48 UTC, MastekRohitChettri commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.FulfilmentService/Services/FulfilmentAncillaryFiles.cs
> +            string file = Path.Combine(filePath, "ENC Updates List.csv");
Resolved

2022-09-05 13:13 UTC, harshal11869 approved these changes
LGTM

2022-09-07 08:05 UTC, ajasonca approved these changes
Looks good

2022-09-08 07:12 UTC, merged