Feature - 74919 ess api response when aio feature on/off
UKHO/exchange-set-service pull request #200
Opened 2023-04-03 04:48 UTC by MastekRohitChettri

- Done code changes
- Added unit test cases
- Added functional tests

2023-04-03 09:19 UTC, shailen14599 requested changes

2023-04-03 09:27 UTC, MastekRohitChettri commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API/appsettings.json
> +    "IsAioEnabled": false,
Resolved

2023-04-04 09:31 UTC, ray-sj approved these changes
looks fine

2023-04-04 12:02 UTC, shailen14599 approved these changes
LGTM

2023-04-04 12:46 UTC, DanOwenUKHO requested changes
Looks good, a couple of minor comments.
Stryker report: 44.48% -> 45.38 %

2023-04-04 12:52 UTC, MastekRohitChettri commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.Common/Models/Response/ExchangeSetResponse.cs
> +        public int? RequestedAioProductCount { get; set; } = null;
Based on Aio toggle when toggle is Off then Aio details in response need to hide. So with above code we are removing null properties and when toggle is On then we are assigning above property which returns as Aio details in ess response.

2023-04-04 13:57 UTC, merged