74619 - ess api additional params calculation when aio feature on
UKHO/exchange-set-service pull request #208
Opened 2023-04-14 07:31 UTC by MastekRohitChettri

- Added code changes
- Added unit test cases
- Added functional tests
- Improve stryker check report

2023-04-17 12:53 UTC, ray-sj approved these changes
looks fine

2023-04-18 10:10 UTC, DanOwenUKHO requested changes
A few questions to address

2023-04-18 10:24 UTC, MastekRohitChettri commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API.UnitTests/Services/ProductDataServiceTests.cs
> +        private static ExchangeSetResponse GetExchangeSetResponseAioToggleOff()
Made private methods static as suggested by dot net compiler to achieve performance gain.
Additionally, these methods can't be use outside so no new instance will require.

2023-04-18 10:24 UTC, MastekRohitChettri commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API.UnitTests/Services/ProductDataServiceTests.cs
> +        private static ExchangeSetResponse GetExchangeSetResponseAioToggleON()
Made private methods static as suggested by dot net compiler to achieve performance gain.
Additionally, these methods can't be use outside so no new instance will requires.

2023-04-18 10:24 UTC, MastekRohitChettri commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API.UnitTests/Services/ProductDataServiceTests.cs
> +        private static SalesCatalogueResponse GetSalesCatalogueFileSizeResponse()
Made private methods static as suggested by dot net compiler to achieve performance gain.
Additionally, these methods can't be use outside so no new instance will requires.

2023-04-18 10:24 UTC, MastekRohitChettri commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API/Services/ProductDataService.cs
> +        private static string ConvertLastModifiedToString(SalesCatalogueResponse salesCatalougeResponse)
Made private methods static as suggested by dot net compiler to achieve performance gain.
Additionally, these methods can't be use outside so no new instance will requires.

2023-04-18 10:29 UTC, MastekRohitChettri commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API/Services/ProductDataService.cs
> +                IEnumerable<string> lstRequestedProducts = request.ProductVersions.Select(x => x.ProductName).ToList();
Additional conversion has been removed.

2023-04-18 10:36 UTC, shailen14599 approved these changes
LGTM

2023-04-18 11:20 UTC, DanOwenUKHO commented
Stryker report ->  44.97 %

2023-04-18 11:20 UTC, DanOwenUKHO approved these changes
LGTM

2023-04-18 12:38 UTC, merged