WIP Dev/144895 create new endpoint to provide product updates since datetime
UKHO/exchange-set-service pull request #277
Opened 2024-03-11 07:45 UTC by pratibh14837

This PR contains coding, unit test cases in WIP.
Please review the same

Thanks

2024-03-11 10:15 UTC, richardAhz requested changes
Can we change  
GetExchangeSetDataProductDateTimeAsync
to
GetExchangeSetProductDataByDateTimeAsync

2024-03-11 10:32 UTC, richardAhz approved these changes
LGTM

2024-03-15 07:14 UTC, gaurav15233 reviewed
Suggested Comments

2024-03-15 07:14 UTC, gaurav15233 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API.UnitTests/UKHO.ExchangeSetService.API.UnitTests.csproj
> -  </ItemGroup>
Please remove this deleted line. This should not be in commit

2024-03-15 10:29 UTC, pratibh14837 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API/Controllers/ProductInformationController.cs
> +
removed blank line

2024-03-15 10:29 UTC, pratibh14837 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API/Controllers/ProductInformationController.cs
> +    [ServiceFilter(typeof(BespokeExchangeSetAuthorizationFilterAttribute))]
resolved

2024-03-15 10:30 UTC, pratibh14837 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API.UnitTests/Controllers/ProductInformationControllerTests.cs
> +
removed

2024-03-15 10:30 UTC, pratibh14837 commented on UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API.UnitTests/Controllers/ProductDataControllerTests.cs
> +
removed

2024-03-15 12:32 UTC, jagannathsankpal approved these changes
LGTM

2024-03-18 16:07 UTC, merged